spring:
  application:
    name: pola

  # ===============================
  # DB Setting
  # ===============================
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://k13d204.p.ssafy.io:5432/pola_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # ===============================
  # JPA Setting
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # ===============================
  # Redis Setting
  # ===============================
  data:
    redis:
      host: redis  # docker-compose의 컨테이너 이름
      port: 6379
      password: ${REDIS_PASSWORD} # .env 파일에서 읽어올 변수

  # ===============================
  # Security & OAuth2
  # ===============================
  security:
    oauth2:
      client:
        registration:
          google-web:
            client-id: ${GOOGLE_WEB_CLIENT_ID}
            client-secret: ${GOOGLE_WEB_CLIENT_SECRET}
            scope: openid, profile, email

          google-android:
            client-id: ${GOOGLE_ANDROID_CLIENT_ID}
            scope: openid, profile, email

        provider:
          google:
            issuer-uri: https://accounts.google.com

  # ===============================
  # JWT Configuration
  # ===============================
  jwt:
    secret: ${JWT_SECRET}
    access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}     # in milliseconds
    refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}   # in milliseconds


# ===============================
# Server Setting
# ===============================
server:
  port: 8080

# ===============================
# logging
# ===============================
logging:
  level:
    org.springframework: INFO
    com.jinjinjara: DEBUG

# ===============================
# Swagger
# ===============================
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# ===============================
# S3
# ===============================
aws:
  credentials:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: pola-storage-bucket
    dir: home
  region:
    static: ap-northeast-2
  stack:
    auto: false